name: "publish"
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-18.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install tauri bundler
        run: cargo install tauri-bundler --force

      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-18.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 libgtk-3-dev libappindicator3-dev

      - name: install app dependencies and build it
        run: yarn && yarn build

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: __VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Smaug Desktop __VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
          includeDebug: false

  #arch:
  #  runs-on: ubuntu-18.04
  #  needs: [publish-tauri]

  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2

  #    - name: Update the package metadata
  #      run: |
  #        awk -i inplace 'BEGINFILE{print "pkgver=${{ github.event.release.tag_name }}"}{print}' pkg/arch/smaug-desktop/PKGBUILD
  #        wget https://github.com/ereborstudios/smaug-desktop/releases/download/${{ github.event.release.tag_name }}/smaug-desktop_${{ github.event.release.tag_name }}_amd64.deb -O pkg/arch/smaug-desktop/smaug-desktop_${{ github.event.release.tag_name }}_amd64.deb
  #        SHA512SUM=$(sha512sum pkg/arch/smaug-desktop/smaug-desktop_${{ github.event.release.tag_name }}_amd64.deb | awk '{print $1}')
  #        awk -v q="'" -v SHA512SUM=$SHA512SUM -i inplace 'BEGINFILE{print "sha512sums_x86_64=(" q SHA512SUM q ")"}{print}' pkg/arch/smaug-desktop/PKGBUILD
  #        cd pkg/arch/smaug-desktop (
  #          makepkg --printsrcinfo > .SRCINFO
  #        )

  #    - name: Verifies and builds the package
  #      uses: 2m/arch-pkgbuild-builder@v1.18
  #      with:
  #        target: 'pkgbuild'
  #        pkgname: 'pkg/arch/smaug-desktop'

  #    - name: Upload Arch Linux release
  #      uses: actions/upload-release-asset@v1
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #      with:
  #        upload_url: '${{ github.event.release.upload_url }}'
  #        asset_path: 'pkg/arch/smaug-desktop/smaug-desktop-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst'
  #        asset_name: 'smaug-desktop-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst'
  #        asset_content_type: application/octet-stream
